doctrine:
    dbal:
        driver:   pdo_pgsql
        host:     "%env(DB_HOST)%"
        port:     "%env(DB_PORT)%"
        dbname:   "%env(DB_NAME)%"
        user:     "%env(DB_USER)%"
        password: "%env(DB_PASSWORD)%"
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            Domain:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/config/mapping/orm/domain'
                prefix: 'Upservice\Domain'
                alias: Domain
            Projections:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/config/mapping/orm/projections'
                prefix: 'Upservice\Infrastructure'
                alias: Projections
