security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        dev:
            pattern: ^/api/test/(_(profiler|wdt)|css|images|js)/
            security: false
            anonymous: true

        login:
            pattern: ^/api/user/login
            stateless: true
            anonymous: true
            json_login:
                check_path: /api/user/login_check
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
                require_previous_session: false

        api:
            pattern: ^/api
            stateless: true
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator
            anonymous: true

    access_control:
        - { path: ^/api/user/(logout|login_check|login|register), roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/user/password/restore, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/_profiler/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/files/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/account/, roles: IS_AUTHENTICATED_FULLY }