# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:


services:
  _defaults:
    autowire: true
    autoconfigure: true


  Upservice\:
    resource: '../src/*'
    exclude: '../src/**/{Migrations,EventSubscriber}'

  ### UI
  Upservice\UI\Http\Rest\Controller\:
    resource: '../src/UI/Http/Rest/Controller/*'
    tags: [ 'controller.service_arguments' ]
