services:
#    parameters:

    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Exceptions,Entity,Migrations,Tests,Kernel.php}'
    #        exclude: '../src/{DependencyInjection,Exceptions,Manager,Model,Repository,EventListener,Service,Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    App\Manager\User\UserManager:
        arguments: ['@fos_user.util.user_manipulator']

    app.message:
        class: Swift_Message
        public: true
        calls:
            - [ setFrom, [ '%env(MAILER_USER)%' ] ]
            - [ setContentType, [ 'text/html' ] ]

    App\Service\Util\AppMailer:
        class: App\Service\Util\AppMailer
        lazy: true
        public: true
        arguments:
            - '@swiftmailer.mailer'
            - '@app.message'

    App\Manager\User\NotificationManager:
        class: App\Manager\User\NotificationManager
        public: true
        arguments:
            - '@App\Service\Util\AppMailer'
            - '@App\Manager\User\UserManager'
            - '@service_container'
            - '@twig'
            - '@doctrine.orm.default_entity_manager'
